### ISSUE TITLE
Doesn't work on Ubuntu 16.04?

### ISSUE THREAD

**Issue by orsomannaro** [qubitstream/phpmyadmin_sql_backup#2]
On Ubuntu 16.04 (default _pyhon 2.7_ and _python 3_installed together), running:

`python3 phpmyadmin_sql_backup.py "https://myhosting.com/phpmyadmin" USERNAME PASSWORD`

with tested URL, USERNAME and PASSWORD, I have this error:

_Error: Could not login - did you provide the correct username / password? (Substring not found: server_export.php)_

**Comment by qubitstream** [comment]
This script is really quite simplistic and does not check whether you provided the correct login URL, looking e.g. like this on [phpMyAdmins Demo page](https://demo.phpmyadmin.net/STABLE/), so be sure to check this.

Speaking of said URL - does downloading an SQL dump from there work for you?
`python3 phpmyadmin_sql_backup.py  "https://demo.phpmyadmin.net/STABLE/" root ""`
(this will download a small sql file, which you can delete afterwards)

**Comment by orsomannaro** [comment]
Please excuse me for taking so long to answer...

Executing your test, the problem is the same:

python3 phpmyadmin_sql_backup.py  "https://demo.phpmyadmin.net/STABLE/" root ""
Error: Could not login - did you provide the correct username / password? (Substring not found: server_export.php)

Unfortunately I doesn't know Python, so I can't modify the code to try some tests.

**Comment by qubitstream** [comment]
Hmm, i tried to reproduce the error on Ubuntu 14.04, 16.04, Arch Linux and Windows, but unfortunately I was not able to reproduce your error.

Does it work when you try downloading the dump via your browser?

**Comment by flo-assling** [comment]
Had the same problem - it will not work if you have a ! in your password... created a new user with only letters & numbers, and worked!

**Comment by qubitstream** [comment]
Yes, if you have special characters (like ! or a whitespace), you have to escape them to be read correctly - this not only applies to this script, but to all shell commands. More info e.g. [here](https://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-in-bash-how-do-we-know-it).
