### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by lunibo** [qubitstream/phpmyadmin_sql_backup#5]
Hey, i tryed to use your script but i got this Error:

File "phpmyadmin_sql_backup.py", line 68
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

Hope i could help you with this

**Comment by qubitstream** [comment]
It seems you're trying to run this under Python **2.x**.

Could you try to run it in an installation of **Python 3**?
